INSERT INTO tb_dept (name, description) VALUES ('Departamento 1', 'Descrição detalhada sobre as atividades que são exercidas e as pessoas que correspondem ao departamento 1');
INSERT INTO tb_dept (name, description) VALUES ('Departamento 1.1', 'Descrição detalhada sobre as atividades que são exercidas e as pessoas que correspondem ao Departamento 1.1');
INSERT INTO tb_dept (name, description) VALUES ('Departamento 1.2', 'Descrição detalhada sobre as atividades que são exercidas e as pessoas que correspondem ao Departamento 1.2');

INSERT INTO tb_dept (name, description) VALUES ('Departamento 2', 'Descrição detalhada sobre as atividades que são exercidas e as pessoas que correspondem ao Departamento 2');
INSERT INTO tb_dept (name, description) VALUES ('Departamento 2.1', 'Descrição detalhada sobre as atividades que são exercidas e as pessoas que correspondem ao Departamento 2.1');
INSERT INTO tb_dept (name, description) VALUES ('Departamento 2.2', 'Descrição detalhada sobre as atividades que são exercidas e as pessoas que correspondem ao Departamento 2.2');

INSERT INTO tb_dept (name, description) VALUES ('Departamento 3', 'Descrição detalhada sobre as atividades que são exercidas e as pessoas que correspondem ao Departamento 3');
INSERT INTO tb_dept (name, description) VALUES ('Departamento 3.1', 'Descrição detalhada sobre as atividades que são exercidas e as pessoas que correspondem ao Departamento 3.1');
INSERT INTO tb_dept (name, description) VALUES ('Departamento 3.1.1', 'Descrição detalhada sobre as atividades que são exercidas e as pessoas que correspondem ao Departamento 3.1.1');
INSERT INTO tb_dept (name, description) VALUES ('Departamento 3.1.2', 'Descrição detalhada sobre as atividades que são exercidas e as pessoas que correspondem ao Departamento 3.1.2');
INSERT INTO tb_dept (name, description) VALUES ('Departamento 3.2', 'Descrição detalhada sobre as atividades que são exercidas e as pessoas que correspondem ao Departamento 3.2');
INSERT INTO tb_dept (name, description) VALUES ('Departamento 3.2.1', 'Descrição detalhada sobre as atividades que são exercidas e as pessoas que correspondem ao Departamento 3.2.1');
INSERT INTO tb_dept (name, description) VALUES ('Departamento 3.2.2', 'Descrição detalhada sobre as atividades que são exercidas e as pessoas que correspondem ao Departamento 3.2.2');

INSERT INTO tb_dept (name, description) VALUES ('Departamento 4', 'Descrição detalhada sobre as atividades que são exercidas e as pessoas que correspondem ao 4');
INSERT INTO tb_dept (name, description) VALUES ('Departamento 4.1', 'Descrição detalhada sobre as atividades que são exercidas e as pessoas que correspondem ao Departamento 4.1');
INSERT INTO tb_dept (name, description) VALUES ('Departamento 4.1.1', 'Descrição detalhada sobre as atividades que são exercidas e as pessoas que correspondem ao Departamento 4.1.1');
INSERT INTO tb_dept (name, description) VALUES ('Departamento 4.1.2', 'Descrição detalhada sobre as atividades que são exercidas e as pessoas que correspondem ao Departamento 4.1.2);
INSERT INTO tb_dept (name, description) VALUES ('Departamento 4.2', 'Descrição detalhada sobre as atividades que são exercidas e as pessoas que correspondem ao Departamento 4.2');
INSERT INTO tb_dept (name, description) VALUES ('Departamento 4.2.1', 'Descrição detalhada sobre as atividades que são exercidas e as pessoas que correspondem ao Departamento 4.2.1');
INSERT INTO tb_dept (name, description) VALUES ('Departamento 4.2.2', 'Descrição detalhada sobre as atividades que são exercidas e as pessoas que correspondem ao Departamento 4.2.2);


INSERT INTO tb_dept_relation (relating_dept, related_dept, description) VALUES (1, 2, 'O Departamento 1 é o departamento que supervisiona o departamento 1.1');
INSERT INTO tb_dept_relation (relating_dept, related_dept, description) VALUES (2, 1, 'O Departamento 1.1 é um subdepartamento supervisionado pelo departamento 1');
INSERT INTO tb_dept_relation (relating_dept, related_dept, description) VALUES (1, 3, 'O Departamento 1 é o departamento que supervisiona o departamento 1.2');
INSERT INTO tb_dept_relation (relating_dept, related_dept, description) VALUES (3, 1, 'O Departamento 1.2 é um subdepartamento supervisionado pelo departamento 1');
INSERT INTO tb_dept_relation (relating_dept, related_dept, description) VALUES (4, 5, 'O Departamento 1 é o departamento que supervisiona o departamento 2.1');
INSERT INTO tb_dept_relation (relating_dept, related_dept, description) VALUES (5, 4, 'O Departamento 2.1 é um subdepartamento supervisionado pelo departamento 2');
INSERT INTO tb_dept_relation (relating_dept, related_dept, description) VALUES (4, 6, 'O Departamento 1 é o departamento que supervisiona o departamento 2.2');
INSERT INTO tb_dept_relation (relating_dept, related_dept, description) VALUES (6, 4, 'O Departamento 2.2 é um subdepartamento supervisionado pelo departamento 2');

INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Jack', 27, 'https://cdn1.iconfinder.com/data/icons/diversity-avatars-volume-01-v2/64/hipster-man-white-512.png', 1);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Ryan', 18, 'https://cdn2.iconfinder.com/data/icons/diversity-avatars-volume-09/64/avatar-boler-suit-african-512.png', 2);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Francis', 32, 'https://cdn2.iconfinder.com/data/icons/diversity-v2-0-volume-01/64/accountant-asian-female-512.png', 1);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Anna', 19, 'https://cdn2.iconfinder.com/data/icons/diversity-v2-0-volume-01/64/artist-asian-female-512.png', 3);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Leonardo', 27, 'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png', 1);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Raquel', 42, 'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png', 2);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Pietra', 23, 'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png', 4);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Rafael', 37, 'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png', 3);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Lyanne', 22, 'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png', 4);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Albert', 40, 'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png', 2);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Joseph', 29, 'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png', 1);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Ellioth', 31, 'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png', 4);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Apollo', 51, 'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png', 1);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Gutierry', 44, 'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png', 2);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Lorenzo', 20, 'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png', 4);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Elizabeth', 38, 'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png', 3);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Helena', 24, 'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png', 4);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Victória', 18, 'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png', 2);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Elenora', 50, 'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png', 1);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Mary', 34, 'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png', 4);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Luccas', 27, 'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png', 1);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Angêlica', 42, 'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png', 2);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Rose', 49, 'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png', 4);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Felipe', 55, 'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png', 3);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Igniz', 19, 'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png', 4);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Billy', 46, 'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png', 2);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Joseph', 21, 'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png', 1);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Osvald', 39, 'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png', 4);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Joel', 50, 'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png', 1);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Tenório', 34, 'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png', 4);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Diana', 27, 'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png', 1);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Luanna', 42, 'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png', 2);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Robert', 49, 'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png', 4);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Leandro', 55, 'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png', 3);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Louis', 19, 'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png', 4);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Hebert', 46, 'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png', 2);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Narciso', 21, 'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png', 1);
INSERT INTO tb_people (name, age, image, dept_id) VALUES ('Caterine', 39, 'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png', 4);
